# Generated by Django 4.2.7 on 2023-12-03 17:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disorder',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
