# Generated by Django 4.2.7 on 2023-12-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disorders', '0002_alter_disorder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='disorder',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='disorder',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
