# Generated by Django 4.2.7 on 2023-12-03 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disorders', '0003_disorder_slug_disorder_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='disorder',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disorder',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
