# Generated by Django 4.2.7 on 2023-12-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disorders', '0005_comment'),
    ]

    operations = [
    ]
