# Generated by Django 4.2.7 on 2023-12-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disorders', '0006_auto_20231203_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
