# Generated by Django 4.2.7 on 2023-12-01 15:40

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Apraxia of Speech', 'Apraxia of Speech'), ('Stuttering – Stammering', 'Stuttering – Stammering'), ('Dysarthria', 'Dysarthria'), ('Lisping', 'Lisping'), ('Spasmodic Dysphonia', 'Spasmodic Dysphonia'), ('Developmental Language Disorder', 'Developmental Language Disorder'), ('Muteness – Selective Mutism', 'Muteness – Selective Mutism'), ('Aphasia', 'Aphasia'), ('Speech Delay', 'Speech Delay')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('therapistID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='')),
                ('location', models.CharField(choices=[('Scotland', 'Scotland'), ('North', 'North'), ('Midlands', 'Midlands'), ('South', 'South'), ('Wales', 'Wales')], max_length=100)),
                ('specialty', models.ManyToManyField(to='resources.specialty')),
            ],
        ),
    ]
