# Generated by Django 4.2.7 on 2023-12-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
