# Generated by Django 4.2.7 on 2023-12-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_therapist_address_therapist_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
